var annotated =
[
    [ "_RFC_ATTRIBUTES", "struct___r_f_c___a_t_t_r_i_b_u_t_e_s.html", "struct___r_f_c___a_t_t_r_i_b_u_t_e_s" ],
    [ "_RFC_AUTHENTICATION_HANDLE", "struct___r_f_c___a_u_t_h_e_n_t_i_c_a_t_i_o_n___h_a_n_d_l_e.html", "struct___r_f_c___a_u_t_h_e_n_t_i_c_a_t_i_o_n___h_a_n_d_l_e" ],
    [ "_RFC_CERTIFICATE_DATA", "struct___r_f_c___c_e_r_t_i_f_i_c_a_t_e___d_a_t_a.html", "struct___r_f_c___c_e_r_t_i_f_i_c_a_t_e___d_a_t_a" ],
    [ "_RFC_CLASS_ATTRIBUTE_DESC", "struct___r_f_c___c_l_a_s_s___a_t_t_r_i_b_u_t_e___d_e_s_c.html", "struct___r_f_c___c_l_a_s_s___a_t_t_r_i_b_u_t_e___d_e_s_c" ],
    [ "_RFC_CLASS_DESC_HANDLE", "struct___r_f_c___c_l_a_s_s___d_e_s_c___h_a_n_d_l_e.html", "struct___r_f_c___c_l_a_s_s___d_e_s_c___h_a_n_d_l_e" ],
    [ "_RFC_CONNECTION_HANDLE", "struct___r_f_c___c_o_n_n_e_c_t_i_o_n___h_a_n_d_l_e.html", "struct___r_f_c___c_o_n_n_e_c_t_i_o_n___h_a_n_d_l_e" ],
    [ "_RFC_CONNECTION_PARAMETER", "struct___r_f_c___c_o_n_n_e_c_t_i_o_n___p_a_r_a_m_e_t_e_r.html", "struct___r_f_c___c_o_n_n_e_c_t_i_o_n___p_a_r_a_m_e_t_e_r" ],
    [ "_RFC_ERROR_INFO", "struct___r_f_c___e_r_r_o_r___i_n_f_o.html", "struct___r_f_c___e_r_r_o_r___i_n_f_o" ],
    [ "_RFC_EXCEPTION_DESC", "struct___r_f_c___e_x_c_e_p_t_i_o_n___d_e_s_c.html", "struct___r_f_c___e_x_c_e_p_t_i_o_n___d_e_s_c" ],
    [ "_RFC_FIELD_DESC", "struct___r_f_c___f_i_e_l_d___d_e_s_c.html", "struct___r_f_c___f_i_e_l_d___d_e_s_c" ],
    [ "_RFC_FUNCTION_DESC_HANDLE", "struct___r_f_c___f_u_n_c_t_i_o_n___d_e_s_c___h_a_n_d_l_e.html", "struct___r_f_c___f_u_n_c_t_i_o_n___d_e_s_c___h_a_n_d_l_e" ],
    [ "_RFC_METADATA_QUERY_RESULT_ENTRY", "struct___r_f_c___m_e_t_a_d_a_t_a___q_u_e_r_y___r_e_s_u_l_t___e_n_t_r_y.html", "struct___r_f_c___m_e_t_a_d_a_t_a___q_u_e_r_y___r_e_s_u_l_t___e_n_t_r_y" ],
    [ "_RFC_PARAMETER_DESC", "struct___r_f_c___p_a_r_a_m_e_t_e_r___d_e_s_c.html", "struct___r_f_c___p_a_r_a_m_e_t_e_r___d_e_s_c" ],
    [ "_RFC_SECURITY_ATTRIBUTES", "struct___r_f_c___s_e_c_u_r_i_t_y___a_t_t_r_i_b_u_t_e_s.html", "struct___r_f_c___s_e_c_u_r_i_t_y___a_t_t_r_i_b_u_t_e_s" ],
    [ "_RFC_SERVER_ATTRIBUTES", "struct___r_f_c___s_e_r_v_e_r___a_t_t_r_i_b_u_t_e_s.html", "struct___r_f_c___s_e_r_v_e_r___a_t_t_r_i_b_u_t_e_s" ],
    [ "_RFC_SERVER_CONTEXT", "struct___r_f_c___s_e_r_v_e_r___c_o_n_t_e_x_t.html", "struct___r_f_c___s_e_r_v_e_r___c_o_n_t_e_x_t" ],
    [ "_RFC_SERVER_HANDLE", "struct___r_f_c___s_e_r_v_e_r___h_a_n_d_l_e.html", "struct___r_f_c___s_e_r_v_e_r___h_a_n_d_l_e" ],
    [ "_RFC_SERVER_MONITOR_DATA", "struct___r_f_c___s_e_r_v_e_r___m_o_n_i_t_o_r___d_a_t_a.html", "struct___r_f_c___s_e_r_v_e_r___m_o_n_i_t_o_r___d_a_t_a" ],
    [ "_RFC_SESSION_CHANGE", "struct___r_f_c___s_e_s_s_i_o_n___c_h_a_n_g_e.html", "struct___r_f_c___s_e_s_s_i_o_n___c_h_a_n_g_e" ],
    [ "_RFC_STATE_CHANGE", "struct___r_f_c___s_t_a_t_e___c_h_a_n_g_e.html", "struct___r_f_c___s_t_a_t_e___c_h_a_n_g_e" ],
    [ "_RFC_THROUGHPUT_HANDLE", "struct___r_f_c___t_h_r_o_u_g_h_p_u_t___h_a_n_d_l_e.html", "struct___r_f_c___t_h_r_o_u_g_h_p_u_t___h_a_n_d_l_e" ],
    [ "_RFC_TRANSACTION_HANDLE", "struct___r_f_c___t_r_a_n_s_a_c_t_i_o_n___h_a_n_d_l_e.html", "struct___r_f_c___t_r_a_n_s_a_c_t_i_o_n___h_a_n_d_l_e" ],
    [ "_RFC_TYPE_DESC_HANDLE", "struct___r_f_c___t_y_p_e___d_e_s_c___h_a_n_d_l_e.html", "struct___r_f_c___t_y_p_e___d_e_s_c___h_a_n_d_l_e" ],
    [ "_RFC_UNIT_ATTRIBUTES", "struct___r_f_c___u_n_i_t___a_t_t_r_i_b_u_t_e_s.html", "struct___r_f_c___u_n_i_t___a_t_t_r_i_b_u_t_e_s" ],
    [ "_RFC_UNIT_HANDLE", "struct___r_f_c___u_n_i_t___h_a_n_d_l_e.html", "struct___r_f_c___u_n_i_t___h_a_n_d_l_e" ],
    [ "_RFC_UNIT_IDENTIFIER", "struct___r_f_c___u_n_i_t___i_d_e_n_t_i_f_i_e_r.html", "struct___r_f_c___u_n_i_t___i_d_e_n_t_i_f_i_e_r" ],
    [ "RFC_ABAP_OBJECT_HANDLE", "struct_r_f_c___a_b_a_p___o_b_j_e_c_t___h_a_n_d_l_e.html", null ],
    [ "RFC_DATA_CONTAINER", "struct_r_f_c___d_a_t_a___c_o_n_t_a_i_n_e_r.html", "struct_r_f_c___d_a_t_a___c_o_n_t_a_i_n_e_r" ],
    [ "RFC_FUNCTION_HANDLE", "struct_r_f_c___f_u_n_c_t_i_o_n___h_a_n_d_l_e.html", null ],
    [ "RFC_STRUCTURE_HANDLE", "struct_r_f_c___s_t_r_u_c_t_u_r_e___h_a_n_d_l_e.html", null ],
    [ "RFC_TABLE_HANDLE", "struct_r_f_c___t_a_b_l_e___h_a_n_d_l_e.html", null ]
];