#!/usr/bin/env bash
# Freya — regenerate the raw CFFI bindings for each FFI module from the PINNED
# headers in extlibs/include/, using c2ffi (PLAN §7, ROADMAP Phase 0).
#
# Inputs:  extlibs/include/<lib>/*.h   (committed; refresh with vendor-headers.sh)
# Outputs: src/ffi/<lib>/generated-bindings.lisp   (.gitignored)
#
# Prerequisites: c2ffi on PATH (https://github.com/rpav/c2ffi). c2ffi must be
# built against a clang/llvm release that compiles its sources cleanly — the
# upstream tip is known not to build against LLVM 18 (a Decl::getBitWidthValue
# API change); use a clang 14-16 toolchain or a c2ffi fork patched for newer
# clang. The Freya build does NOT require c2ffi: hand-written sample bindings in
# src/ffi/<lib>/bindings.lisp exercise the FFI plumbing today, and the generated
# bindings load on top when present.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INCLUDE="${ROOT}/extlibs/include"
SRC="${ROOT}/src/ffi"

if ! command -v c2ffi >/dev/null 2>&1; then
    cat >&2 <<EOF
gen-bindings: c2ffi not found on PATH.

Install c2ffi from https://github.com/rpav/c2ffi (CMake + clang/llvm dev).
Note: upstream tip does not build against LLVM 18 — use clang/llvm 14-16
(e.g. on Debian/Ubuntu: apt install clang-15 libclang-15-dev llvm-15-dev,
then CC=clang-15 CXX=clang++-15 cmake .. -DBUILD_CONFIG=Release).
EOF
    exit 1
fi

# --- wgpu-native -----------------------------------------------------------
WGPU_HEADERS_DIR="${INCLUDE}/wgpu"
WGPU_OUT="${SRC}/wgpu/generated-bindings.lisp"

if [[ ! -f "${WGPU_HEADERS_DIR}/wgpu.h" ]]; then
    echo "==> wgpu headers missing — run scripts/vendor-headers.sh first" >&2
    exit 2
fi

echo "==> Generating wgpu-native bindings"
# Emit JSON spec, then convert to CFFI defcfun forms via the c2ffi lisp output.
# c2ffi's --output-format=sexp produces s-expressions; for full CFFI integration
# we rely on cffi/c2ffi's loader, which consumes the json spec at compile time.
# Here we generate the spec; the cffi/c2ffi machinery handles the rest.
c2ffi \
    -M "${SRC}/wgpu/generated-macros.lisp" \
    -o "${WGPU_OUT%.lisp}.spec" \
    "${WGPU_HEADERS_DIR}/wgpu.h"

cat > "${WGPU_OUT}" <<'EOF'
;;; AUTO-GENERATED by scripts/gen-bindings.sh — do not edit by hand.
;;; Loads the c2ffi spec produced for the pinned wgpu-native headers.
(in-package #:net.goenninger.freya.ffi.wgpu.raw)
(cffi/c2ffi:c2ffi-spec
  (asdf:system-relative-pathname "net.goenninger.freya/ffi-wgpu"
                                 "generated-bindings.spec"))
EOF

echo "    -> ${WGPU_OUT}"
echo
echo "Done. Re-load .../ffi-wgpu in your Lisp; the generated bindings will be"
echo "picked up automatically by src/ffi/wgpu/bindings.lisp."
